---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 99g
  name: git
spec:
  rules:
    - host: git.localhost
      http:
        paths:
          - backend:
              service:
                name: git
                port:
                  number: 80
            path: /
            pathType: Prefix

---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: git
  name: git
spec:
  ports:
    - port: 80
      protocol: TCP
  selector:
    app: git

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: git
  name: git
spec:
  replicas: 1
  selector:
    matchLabels:
      app: git
  serviceName: git
  template:
    metadata:
      labels:
        app: git
    spec:
      containers:
        - image: git:latest
          imagePullPolicy: Never
          name: git
          ports:
            - containerPort: 80
              name: web
              protocol: TCP
          volumeMounts:
            - mountPath: /var/www/htdocs/git
              name: git
      volumes:
        - emptyDir: {}
          name: git
