---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: ingress-nginx
  namespace: kube-system
spec:
  chart: ingress-nginx
  repo: https://kubernetes.github.io/ingress-nginx
  targetNamespace: kube-system
  valuesContent: |-
    controller:
      ingressClassResource:
        default: true
      watchIngressWithoutClass: true
