---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gotk-components.yaml
  - gotk-sync.yaml
patches:
  - patch: |-
      - op: replace
        path: /spec/interval
        value: 15s
    target:
      kind: (GitRepository|Kustomization)
      name: flux-system
  - patch: |-
      - op: replace
        path: /spec/url
        value: http://git@git.default.svc/k8s-localdev.git
    target:
      kind: GitRepository
      name: flux-system
patchesStrategicMerge:
  - |-
    kind: GitRepository
    apiVersion: source.toolkit.fluxcd.io/v1beta2
    metadata:
      name: flux-system
      namespace: flux-system
    spec:
      secretRef:
        $patch: delete
