---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: k8s-localdev
  namespace: flux-system
spec:
  interval: 15s
  path: ./kustomize
  prune: true
  serviceAccountName: kustomize-controller
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNameSpace: default
